### ISSUE TITLE
Roadmap of package?

### ISSUE THREAD

**Issue by cgpu** [jhrcook/HotNetvieweR#1]
Hi Joshua,

I would be interested to test your R take on this visualisation. Can you guide me through how to run it?

Any chance if have a script before the package is ready?

**Comment by jhrcook** [comment]
Hello,
At the moment, I haven't made any progress in getting this into the shape of a package.

The script "R/TEMP_original_fxns.R" can be run by passing the path of your HotNet2 results directory to `get_HN2_subnetworks()`. Currently, the p-value cut-offs are hardcoded, but you are welcome to change them in your fork.

Since you've expressed interest in using this package, I may go ahead and try to tackle it this weekend.

Best,
Josh

**Comment by cgpu** [comment]
Hi Joshua, 

Thanks for the response.
I have run the function with an example.
The object is created successfully I believe.

This is what I did:
```bash
git clone https://github.com/cgpu/HotNet2-examples.git
```

I uploaded my example output there so that you will be able to reproduce if needed.
I then opened Rstudio and did the following:

(**NOTE**: I did not change your variable names in case you have a script that uses them, to be able to check without having to change anything prior to running the commands)

```r
source("https://raw.githubusercontent.com/jhrcook/HotNetvieweR/master/R/TEMP_original_fxns.R")

# using the folder from https://github.com/cgpu/HotNet2-examples.git
coad_a146t_path <- "results/HotNet2/networka-example/"
coad_a146t_hn2 <- get_HN2_subnetworks(coad_a146t_path)
```
This is how the object looks like:

```r
> coad_a146t_hn2
$sample_name
[1] "networka-example"

$delta
[1] 0.06690436

$size
[1] 4

$subnetworks
# A tbl_graph: 18 nodes and 58 edges
#
# An undirected simple graph with 3 components
#
# Edge Data: 58 x 2 (active)
   from    to
  <int> <int>
1     1     2
2     1     3
3     1     4
4     1     5
5     1     6
6     1     7
# … with 52 more rows
#
# Node Data: 18 x 2
  name       uuid
  <chr>     <int>
1 gene18 80894382
2 gene19 80894382
3 gene20 80894382
# … with 15 more rows

```

Do I need to call another function to plot the graph? Do you have a typical command that you use?

Thanks in advance for the help and let me know if you need more details to be able to help.

Christina

**Comment by jhrcook** [comment]
Hey Christina, 

Nicely done! I'm impressed that someone else was able to use my code that wasn't written to be used in a general case (ie. not as a package).

For plotting, the `coad_a146t_hn2$subnetworks` is already a `tidygraph` object, so you can actually just plot that using `plot()`. For a better figure, I would recommend using the 'ggraph' package. However, the graph in `coad_a146t_hn2$subnetworks` is just a bunch of fully-connected components, one for each subnetwork identified by HotNet2. Therefore, plotting it won't be very interesting. Let me work on that this weekend and see what I can come up with. Ideally, the user could include their original network (even by just pointing to the location of the input files for HotNet (the edge lists and gene indices)) and a function would plot the subnetworks identified by HotNet using the input PPI.

For now, you can get the HotNet2 results out by separating the `$subnetworks` object by component and getting the node names. This might already be reflected by the `uuid` column of the nodes tibble, but I don't recall exactly. If that is the case, then you can get that data using `tidygraph::as_tibble(coad_a146t_hn2$subnetworks, active = "nodes")`.

Hopefully that can get you started, but I'll try to get going this weekend and get back to you with some useful features.


Josh

**Comment by cgpu** [comment]
> Hi Joshua,
> 
> Thanks for the response.
> I have run the function with an example.
> The object is created successfully I believe.
> 
> This is what I did:
> 
> ```shell
> git clone https://github.com/cgpu/HotNet2-examples.git
> ```
> 
> I uploaded my example output there so that you will be able to reproduce if needed.
> I then opened Rstudio and did the following:
> 
> (**NOTE**: I did not change your variable names in case you have a script that uses them, to be able to check without having to change anything prior to running the commands)
> 
> ```r
> source("https://raw.githubusercontent.com/jhrcook/HotNetvieweR/master/R/TEMP_original_fxns.R")
> 
> # using the folder from https://github.com/cgpu/HotNet2-examples.git
> coad_a146t_path <- "results/HotNet2/networka-example/"
> coad_a146t_hn2 <- get_HN2_subnetworks(coad_a146t_path)
> ```
> 
> This is how the object looks like:
> 
> ```r
> > coad_a146t_hn2
> $sample_name
> [1] "networka-example"
> 
> $delta
> [1] 0.06690436
> 
> $size
> [1] 4
> 
> $subnetworks
> # A tbl_graph: 18 nodes and 58 edges
> #
> # An undirected simple graph with 3 components
> #
> # Edge Data: 58 x 2 (active)
>    from    to
>   <int> <int>
> 1     1     2
> 2     1     3
> 3     1     4
> 4     1     5
> 5     1     6
> 6     1     7
> # … with 52 more rows
> #
> # Node Data: 18 x 2
>   name       uuid
>   <chr>     <int>
> 1 gene18 80894382
> 2 gene19 80894382
> 3 gene20 80894382
> # … with 15 more rows
> ```
> 
> Do I need to call another function to plot the graph? Do you have a typical command that you use?
> 
> Thanks in advance for the help and let me know if you need more details to be able to help.
> 
> Christina

**Comment by cgpu** [comment]
Joshua, 

Thank you for the prompt response once again!

I played around a bit with `ggraph` and this is my result:

![image](https://user-images.githubusercontent.com/38183826/66661952-cee94680-ec3f-11e9-9132-e47d8953088f.png)

```r
# snippet that generated the plot

library(ggraph)

hotnet2_graph <- coad_a146t_hn2$subnetworks
hotnet2_graph %>% 
  activate(edges) %>% 
  activate(nodes) %>%
  ggraph(layout = 'kk') + 
  theme_graph() +
  geom_edge_link() + 
  geom_node_point(aes(colour = name), size = 7, show.legend = FALSE) +
  geom_node_label(aes(label = name),  repel = TRUE) +
  theme_graph()
```
Would be very interested to see the progression of your project so definitely let me know if you would like a tester or contributor, I would be happy to use the package. 

I checked a bit [`tidygraph`](https://www.data-imaginist.com/2017/introducing-tidygraph/) and the functions for binding and merging graphs might be handy.

![image](https://user-images.githubusercontent.com/38183826/66662257-65b60300-ec40-11e9-9acd-00edd9a147fb.png)


Best,
Christina

**Comment by cgpu** [comment]
Hi Joshua,

I made some progress today. The subnetworks reflected in the components of the `tbl_graph` are not convoluted for this one as the previous snippet I shared with `ggraph`. 

![image](https://user-images.githubusercontent.com/38183826/66707146-13560e80-ed34-11e9-9b0e-6025f8f9f2a0.png)

Starting to get very fond of `visNetwork`. 

Here is the snippet I used to generate the above networks:

```r
library("visNetwork")
source("https://raw.githubusercontent.com/jhrcook/HotNetvieweR/master/R/TEMP_original_fxns.R")

hotnet2_results_network_heat_folder_path <- "results/HotNet2/networka-example/"
hotnet2_results_network_heat             <- get_HN2_subnetworks(hotnet2_results_network_heat_folder_path)

hotnet2_results_network_heat$subnetworks %>%
  activate(nodes) %>%
  as.igraph() %>%
  visIgraph(idToLabel = FALSE) %>% 
  visOptions(highlightNearest = TRUE) %>%
  visNodes(color = list(background   = '#74B3D5', 
                        border       = '#4C9EC9',
                        highlight    = '#AD88B3'),
         shadow = list(enabled = TRUE, size = 10)) %>%
  visEdges(color = list(background   = '#74B3D5', 
                        border       = '#4C9EC9',
                        highlight    = '#AD88B3'),
           shadow = list(enabled = TRUE, size = 10)) %>%
  visLayout(randomSeed = 12)  %>%
  
  visOptions(highlightNearest = TRUE, 
             nodesIdSelection = TRUE) %>%
  
  visInteraction(navigationButtons = FALSE, 
                 selectConnectedEdges = TRUE, 
                 dragNodes = TRUE, 
                 dragView = FALSE, 
                 zoomView = FALSE, #
                 hideEdgesOnDrag = FALSE, 
                 hideNodesOnDrag = NULL, 
                 hover = TRUE,
                 hoverConnectedEdges = TRUE,
                 keyboard = TRUE, 
                 multiselect = TRUE,
                 selectable = TRUE,
                 tooltipDelay = NULL,
                 tooltipStay = 300, 
                 tooltipStyle = NULL)

```

I found a lot of nice examples in the following resources:

- https://www.visibledata.co.uk/blog/2018/02/27/2018-02-27-crawling-with-tidygraph/
- https://rpubs.com/niyer/389851

**Comment by jhrcook** [comment]
Those look great! They are interactive too, right? 
Keep track of your work on this downstream visualization. After I can get the package's framework in place, you can update these scripts and bring them in as functions in a PR.

**Comment by cgpu** [comment]
That sounds great! More than happy to contribute and thanks for sharing `HotNetvieweR` in the first place, much appreciated.
